### ISSUE TITLE
Crash when changing directories 

### ISSUE THREAD

**Issue by jdevora** [Nutomic/syncthing-lite#11] opened 2018-01-07 10:55 UTC
After many tries, I managed to add a device on the same network.
I kept trying and it finally synchronized the list of folders
Now I get this crash when I try to enter in one of the folders

```
01-07 10:48:00.977   938   938 D AndroidRuntime: Shutting down VM
01-07 10:48:00.992   938   938 E AndroidRuntime: FATAL EXCEPTION: main
01-07 10:48:00.992   938   938 E AndroidRuntime: Process: net.syncthing.lite, PID: 938
01-07 10:48:00.992   938   938 E AndroidRuntime: java.lang.IllegalStateException: activity is already destroyed
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity.folderBrowser(SyncthingActivity.kt:42)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at net.syncthing.lite.activities.FolderBrowserActivity$onFolderChanged$1.run(FolderBrowserActivity.kt:123)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6274)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-07 10:48:00.992   938   938 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-07 10:48:00.994  2133  3171 D ActivityManager: New dropbox entry: net.syncthing.lite, data_app_crash, 34e19f8e-5fbd-4c58-b961-e03ed19bdde8
01-07 10:48:00.995  2133  3171 W ActivityManager:   Force finishing activity net.syncthing.lite/.activities.MainActivity
01-07 10:48:01.000  2133  3171 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
01-07 10:48:01.070   938  2098 I IndexBrowser: folder preload END for folder = 'dlaiz-3srsf' path = ''
01-07 10:48:01.070   938  2098 I IndexBrowser: cache ready, notify listeners
01-07 10:48:01.079  2133  2168 I InputDispatcher: Focus entered window: Window{bf6ef1a u0 Application Error: net.syncthing.lite}
01-07 10:48:01.098  2133  2133 I BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) },4]
01-07 10:48:01.103   686   686 D clmlib  : Got activities:0x00000008
01-07 10:48:01.103   686   686 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1515322081097.txt processName: net.syncthing.lite
01-07 10:48:01.103   686   742 I JavaDumper:JavaDumperThread: Event: data_app_crash@1515322081097.txt TimeStamp: 1515322081
01-07 10:48:01.111  2133 20375 I OpenGLRenderer: Initialized EGL, version 1.4
01-07 10:48:01.111  2133 20375 D OpenGLRenderer: Swap behavior 1
01-07 10:48:01.155   686   742 W JavaDumper:JavaDumper: Could not init dump dir: Unknown error -95
01-07 10:48:01.156   686   742 E JavaDumper:FW:  utils.c(256): mkdir (/data/crashdata) failed. File exists
01-07 10:48:01.189   686   742 E JavaDumper:FW:  ramdump_framework.c(317): fp is NULL
01-07 10:48:01.189   686   742 E JavaDumper:FW:  ramdump_framework.c(498): Read-only file system
01-07 10:48:01.224  2133  2002 I ActivityManager: Start proc 2199:com.sonyericsson.crashmonitor/1000 for broadcast com.sonyericsson.crashmonitor/.receiver.CrashMonitorServiceBroadcastReceiver
01-07 10:48:01.269   686   742 E JavaDumper:FW:  JavaDumper.cpp(262): Failed to remove /tmp/dropbox.txt:Unknown error -2
01-07 10:48:01.322  2133  2171 I BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitorsystemservice.DIR_UPDATED flg=0x10 (has extras) },2]
01-07 10:48:01.500  2133  2167 W ActivityManager: Activity pause timeout for ActivityRecord{38db361 u0 net.syncthing.lite/.activities.MainActivity t11581 f}
```
  
Another crash reports after I restarted the App
```
01-07 11:26:24.884  6494  6494 D AndroidRuntime: Shutting down VM
01-07 11:26:24.885  6494  6494 E AndroidRuntime: FATAL EXCEPTION: main
01-07 11:26:24.885  6494  6494 E AndroidRuntime: Process: net.syncthing.lite, PID: 6494
01-07 11:26:24.885  6494  6494 E AndroidRuntime: java.lang.IllegalArgumentException: View=DecorView@741219c[] not attached to window manager
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:470)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:379)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.app.Dialog.dismissDialog(Dialog.java:370)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.app.Dialog.dismiss(Dialog.java:353)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.app.Dialog.cancel(Dialog.java:1226)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity.onLibraryLoaded(SyncthingActivity.kt:78)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity.access$onLibraryLoaded(SyncthingActivity.kt:19)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity$onCreate$1.invoke(SyncthingActivity.kt:58)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.activities.SyncthingActivity$onCreate$1.invoke(SyncthingActivity.kt:19)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.library.InitLibraryTask$1$2.invoke(InitLibraryTask.kt:39)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at net.syncthing.lite.library.InitLibraryTask$1$2.invoke(InitLibraryTask.kt:11)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at org.jetbrains.anko.AsyncKt$uiThread$1.run(Async.kt:70)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6274)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-07 11:26:24.885  6494  6494 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-07 11:26:24.889  2133  2775 D ActivityManager: New dropbox entry: net.syncthing.lite, data_app_crash, e2c8b7d8-73c9-4733-a234-572918a0ba79
01-07 11:26:24.890  2133  2775 W ActivityManager:   Force finishing activity net.syncthing.lite/.activities.MainActivity
01-07 11:26:24.897  2133  2775 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
01-07 11:26:24.915   686   686 D clmlib  : Got activities:0x00000008
01-07 11:26:24.915   686   686 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1515324384914.txt processName: net.syncthing.lite
01-07 11:26:24.916   686   742 I JavaDumper:JavaDumperThread: Event: data_app_crash@1515324384914.txt TimeStamp: 1515324384
01-07 11:26:24.916  2133  2133 I BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) },4]
```
And this other crash when I tried to download a file
```
8456  8467 I art     : Background sticky concurrent mark sweep GC freed 483381(15MB) AllocSpace objects, 0(0B) LOS objects, 25% free, 29MB/39MB, paused 10.605ms total 145.526ms
01-07 11:38:51.930  8456  8456 D FolderBrowserActivity: navigate to path = 'Internet/Conf/Accts/Acc.kdbx' from path = 'Internet/Conf/Accts'
01-07 11:38:51.930  8456  8456 I FolderBrowserActivity: pulling file = FileRecord{folder=dlaiz-3srsf, path=Internet/Conf/Accts/Acc.kdbx, size=448318, lastModified=Sun Jan 07 09:34:53 GMT+00:00 2018, type=FILE, last version = Version{id=-7232588831173444042, value=46}}
01-07 11:38:51.970  2133  3170 I InputDispatcher: Focus entered window: Window{7e28de5 u0 net.syncthing.lite/net.syncthing.lite.activities.FolderBrowserActivity}
01-07 11:38:55.556   882   882 I MSM-irqbalance: Decided to move IRQ132 from CPU0 to CPU1
01-07 11:38:55.754  8456  8489 I DiscoveryHandler: received device address list from local discovery
01-07 11:38:55.755  8456  8490 I DiscoveryHandler: processing device address list
01-07 11:38:56.016  1684  1684 W glodThread: type=1400 audit(0.0:12407): avc: denied { read } for name="gpubusy" dev="sysfs" ino=13783 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 ppid=691 pcomm="main" pgid=10786 pgcomm="terycalibration"
01-07 11:38:56.684 10586 10677 D ClClient: Not sending keepalive.  Current connection state=STOPPED
01-07 11:39:00.005  2133  2381 I BroadcastQueue: am_broadcast_enqueue: [foreground,1,Intent { act=android.intent.action.TIME_TICK flg=0x50000014 (has extras) },16]
01-07 11:39:00.010  2511  2511 D KeyguardUpdateMonitor: received broadcast android.intent.action.TIME_TICK
01-07 11:39:00.010  2511  2511 D KeyguardUpdateMonitor: handleTimeUpdate
01-07 11:39:02.936 10786  8540 W CursorWindow: Window is full: requested allocation 36 bytes, free space 34 bytes, window size 2097152 bytes
01-07 11:39:06.701 10586 10677 D ClClient: Not sending keepalive.  Current connection state=STOPPED
01-07 11:39:08.558  8456  8489 I DiscoveryHandler: received device address list from local discovery
01-07 11:39:08.558  8456  8490 I DiscoveryHandler: processing device address list
01-07 11:39:09.514  2133  9914 W SettingsProvider: You shouldn't keep your settings in the secure settings. This will soon become an error.
01-07 11:39:10.550   882   882 I MSM-irqbalance: Decided to move IRQ222 from CPU0 to CPU1
01-07 11:39:11.826   972   972 W ipacm   : type=1400 audit(0.0:12415): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=953 pgcomm="ipacm"
01-07 11:39:11.826   972   972 W ipacm   : type=1400 audit(0.0:12416): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=953 pgcomm="ipacm"
01-07 11:39:11.826   972   972 W ipacm   : type=1400 audit(0.0:12417): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=953 pgcomm="ipacm"
01-07 11:39:11.826   971   971 W ipacm   : type=1400 audit(0.0:12418): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=953 pgcomm="ipacm"
01-07 11:39:11.826   971   971 W ipacm   : type=1400 audit(0.0:12419): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=953 pgcomm="ipacm"
01-07 11:39:15.549   882   882 I MSM-irqbalance: Decided to move IRQ57 from CPU0 to CPU1
01-07 11:39:16.704 10586 10677 D ClClient: Not sending keepalive.  Current connection state=STOPPED
01-07 11:39:26.700 10586 10677 D ClClient: Not sending keepalive.  Current connection state=STOPPED
01-07 11:39:26.986  8456  8531 E AndroidRuntime: FATAL EXCEPTION: Thread-5
01-07 11:39:26.986  8456  8531 E AndroidRuntime: Process: net.syncthing.lite, PID: 8456
01-07 11:39:26.986  8456  8531 E AndroidRuntime: java.lang.IllegalArgumentException: unable to aquire index from connection BlockExchangeConnectionHandler{address=DeviceAddress{deviceId=CWZYA7U-N3PFJGE-U34A57G-TBNYRCY-RTVCK7T-CGRINRT-PLZ3LBU-YWYJFA7, instanceId=3274518355111554650, address=tcp://192.168.62.104:22000}, lastActive=46.314secs ago}, timeout reached!
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.bep.IndexHandler.waitForRemoteIndexAquired(IndexHandler.java:122)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.bep.IndexHandler.waitForRemoteIndexAquired(IndexHandler.java:114)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.client.SyncthingClient$pullFile$1.invoke(SyncthingClient.kt:173)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.client.SyncthingClient$pullFile$1.invoke(SyncthingClient.kt:48)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.client.SyncthingClient$getConnectionForFolder$1.invoke(SyncthingClient.kt:115)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.client.SyncthingClient$getConnectionForFolder$1.invoke(SyncthingClient.kt:48)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at net.syncthing.java.client.SyncthingClient$getPeerConnections$1.run(SyncthingClient.kt:139)
01-07 11:39:26.986  8456  8531 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Nutomic** [comment] 2018-01-09 05:54
I've fixed the first and second crash. Not quite sure what the problem is with the third crash, so that will take some more time.

**Comment by Nutomic** [comment] 2018-01-29 13:02
Should be all fixed now.

**Closed by Nutomic** 2018-01-29 13:02 UTC
